version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cd dist
      - zip -r ../output.zip frontend package.json server.js
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'