# see https://medium.com/@AlexanderObregon/building-type-safe-apis-with-typescript-and-openapi-1f78b4b94ee4
openapi: 3.0.0
info:
  title: CollectiveGood Backend API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Logins a user in
      responses:
        "200":
          description: returns a login cookie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: failed to login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"

  /logout:
    post:
      summary: logs a user out
      responses:
        "200":
          description: logs a user out
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"

        "500":
          description: Server failed to finish the function
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
  /signup:
    post:
      summary: Logins a user in
      requestBody:
        required: true
        content:
          application/json:
            $ref: "#/components/schemas/SignUpInput"
      responses:
        "200":
          description: signs a user up and returns the cookie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          description: Server failed to finish the function
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
  /getCase/:hash:
    get:
      summary: gets a case from the url hash

components:
  schemas:
    Response:
      type: object
      properties:
        response:
          type: string
      required:
        - response
    User:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
        password:
          type: string
        name:
          type: string
        role:
          type: string
      required:
        - id
        - email
        - password
        - name
        - role
    SignUpInput:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        email:
          type: string
      required:
        - email
        - password
        - name
